services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    stdin_open: true
    tty: true
    environment:
      - ENV=development
    working_dir: /app
    command: /bin/bash
